name: keybr build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            SDK_ROOT:
          - ARCH: arm64
            SDK_ROOT: SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          mkdir build
          cd build/
          cmake ..
          make -j4
        name: Build on macOS

  freebsd:
    name: FreeBSD (x64)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.3
        name: Build on FreeBSD
        with:
          usesh: true
          mem: 4096
          prepare: |
            pkg install -y cmake
          run: |
            mkdir build
            cd build/
            cmake ..
            make -j4
